version: '3.7'

networks:
  kong-net:

volumes:
  kong_database:

services:
  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    networks:
      - kong-net
    environment:
      POSTGRES_USER: konguser
      POSTGRES_PASSWORD: kongpassword
      POSTGRES_DB: db_kong
    ports:
      - "5432"
    volumes:
      - kong_database:/var/lib/postgresql/data

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong/kong-gateway:2.8.0.0-alpine
    container_name: kong-migration
    entrypoint: sh -c "sleep 10 && kong migrations bootstrap -v"
    networks:
      - kong-net
    restart: on-failure
    environment:
        KONG_PG_HOST: kong-database #container link name
        KONG_PG_DATABASE: db_kong
        KONG_PG_USER: konguser
        KONG_PG_PASSWORD: kongpassword
    links:
      - kong-database
    depends_on:
      - kong-database
      
  #######################################
  # Kong : The API Gateway
  #######################################
  kong-gateway:
    #image: kong:latest
    image: kong/kong-gateway:2.8.0.0-alpine
    container_name: kong-gateway
    networks:
      - kong-net
    volumes:
      - ./kong-configuration/kong_declarative_conf.yml:/usr/local/kong/declarative/kong.yml
    environment:
        KONG_DATABASE: postgres #Type of database
        KONG_PG_HOST: kong-database #container link name
        KONG_PG_DATABASE: db_kong
        KONG_PG_USER: konguser
        KONG_PG_PASSWORD: kongpassword
        KONG_PROXY_ACCESS_LOG: /dev/stdout
        KONG_ADMIN_ACCESS_LOG: /dev/stdout
        KONG_PROXY_ERROR_LOG: /dev/stderr
        KONG_ADMIN_ERROR_LOG: /dev/stderr
        KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    restart: always
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8100:8100
      - 8002:8002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong-gateway:8001"]
      interval: 5s
      timeout: 2s
      retries: 15